export const LANGUAGES_OPTIONS = [
    { value: '__all__', labelKey: 'filters.all_languages', icon: '🌍' },
    { value: 'javascript', label: 'JavaScript', icon: '🚀' },
    { value: 'typescript', label: 'TypeScript', icon: '📘' },
    { value: 'python', label: 'Python', icon: '🐍' },
    { value: 'java', label: 'Java', icon: '☕' },
    { value: 'cpp', label: 'C++', icon: '⚡' },
    { value: 'html', label: 'HTML', icon: '🌐' },
    { value: 'css', label: 'CSS', icon: '🎨' },
    { value: 'php', label: 'PHP', icon: '🐘' },
    { value: 'ruby', label: 'Ruby', icon: '💎' },
    { value: 'go', label: 'Go', icon: '🐹' },
    { value: 'rust', label: 'Rust', icon: '🦀' },
    { value: 'sql', label: 'SQL', icon: '🗄️' },
    { value: 'swift', label: 'Swift', icon: '🐦' },
    { value: 'kotlin', label: 'Kotlin', icon: '🤖' },
    { value: 'dart', label: 'Dart', icon: '🎯' },
]

export const TAGS_OPTIONS = [
    { value: '__all__', labelKey: 'filters.all_tags', category: 'all' },
    { value: 'react', label: 'React', category: 'frontend' },
    { value: 'vue', label: 'Vue.js', category: 'frontend' },
    { value: 'angular', label: 'Angular', category: 'frontend' },
    { value: 'node', label: 'Node.js', category: 'backend' },
    { value: 'express', label: 'Express', category: 'backend' },
    { value: 'nestjs', label: 'NestJS', category: 'backend' },
    { value: 'database', label: 'Database', category: 'data' },
    { value: 'api', label: 'API', category: 'backend' },
    { value: 'auth', label: 'Authentication', category: 'security' },
    { value: 'hook', label: 'Hooks', category: 'react' },
    { value: 'component', label: 'Components', category: 'ui' },
    { value: 'utility', label: 'Utilities', category: 'tools' },
    { value: 'algorithm', label: 'Algorithms', category: 'logic' },
    { value: 'performance', label: 'Performance', category: 'optimization' },
    { value: 'testing', label: 'Testing', category: 'quality' },
    { value: 'typescript', label: 'TypeScript', category: 'language' },
    { value: 'mobile', label: 'Mobile', category: 'platform' },
    { value: 'desktop', label: 'Desktop', category: 'platform' },
    { value: 'cloud', label: 'Cloud', category: 'infrastructure' },
    { value: 'devops', label: 'DevOps', category: 'operations' },
]
